services:
  db:
    image: mysql:8
    container_name: mysql-backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: spring-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15

  frontend:
    build:
      context: ../Compra-tu-Hogar-frontend
      dockerfile: Dockerfile
      target: build # <-- Le dice a Docker que se detenga en la etapa de Node y no use Nginx
    container_name: node-frontend
    ports:
      - "5173:5173" # <-- Cambiado al puerto de desarrollo de Vite
    volumes:
      - ../Compra-tu-Hogar-frontend:/app # <-- Sincroniza tus cambios de código de Windows
      - /app/node_modules # <-- Protege tus dependencias
    environment:
      - VITE_API_URL=/api/v1
    # <-- Sobrescribe el comando de producción para iniciar el servidor de desarrollo de Vite
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      # <-- Ahora el curl verifica el puerto de desarrollo 5173 en lugar del 80
      test: ["CMD-SHELL", "curl -f http://localhost:5173/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6

  cypress:
    image: cypress/included:13.10.0
    container_name: cypress-tests
    network_mode: "host"
    depends_on:
      frontend:
        condition: service_healthy # Cypress espera al frontend (que a su vez esperó a Spring)
    environment:
      - CYPRESS_BASE_URL=http://localhost:5173
    working_dir: /app
    volumes:
      - ../Compra-tu-Hogar-frontend:/app

volumes:
  mysql_data:
  uploads_data:
