services:
  db:
    image: mysql:8
    container_name: mysql-backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: bautistabracco/compra-tu-hogar-backend:latest
    container_name: spring-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}

  frontend:
    image: bautistabracco/compra-tu-hogar-frontend:latest
    container_name: web-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    # TODO(frontend): define env vars and runtime command once frontend Docker image is ready.

volumes:
  mysql_data:
