services:
  db:
    image: mysql:8
    container_name: mysql-backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: spring-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15

  frontend:
    image: node:20-alpine
    container_name: node-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ../Compra-tu-Hogar-frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      backend:
        condition: service_healthy # El frontend no arranca hasta que Spring esté SANO
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 5s
      timeout: 5s
      retries: 6

  cypress:
    image: cypress/included:13.10.0
    container_name: cypress-tests
    network_mode: "host"
    depends_on:
      frontend:
        condition: service_healthy # Cypress espera al frontend (que a su vez esperó a Spring)
    environment:
      - CYPRESS_BASE_URL=http://localhost:5173
    working_dir: /app
    volumes:
      - ../Compra-tu-Hogar-frontend:/app

volumes:
  mysql_data:
  uploads_data:
